name: Publish npm package

on:
  push:
    branches: master # Replace with branches that trigger the workflow (e.g., main)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Authentication Step using npm adduser
      - run: |
          npm adduser --registry https://npm.pkg.github.com --username pavan-dulam --always-auth
          # Optionally store token in npmrc (for convenience, NOT recommended):
          # echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc

      # Install dependencies
      - run: npm install

      # Build and test (add your specific commands here)
      - run: npm run build && npm test

      # Publish step
      - run: |
          npm publish --access public # Replace with private access if needed
        # Or:
        # npm publish --registry https://npm.pkg.github.com @pavan-dulam/microservice-commons # For scoped package

