name: Publish to npm

on:
  push:
    branches:
      - master  # Trigger the workflow when a push is made to the master branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm ci

      - name: Login to npm
        run: npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name: Publish to npm
        run: npm publish
