name: Publish npm package

on:
  push:
    branches: master # Replace with branches that trigger the workflow (e.g., main)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        working-directory: microservice-commons
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
